### ISSUE TITLE
Rename to draft-js-utils

### ISSUE THREAD

**Issue by nikgraf** [draft-js-utils/draft-js-utils#1]
I would suggest to rename it to draft-js-utils and then republish it on npm.

For npm it's probably best if you publish it and then add others as owner. There is a command to do so: https://docs.npmjs.com/cli/owner

This should work `npm owner add nikgraf`.

**Comment by jaaberg** [comment]
I like draft-js-utils best as well :+1: Probably better to do it sooner than later if we are going to change.

**Comment by sstur** [comment]
Done.
