### ISSUE TITLE
Move some other `draft-js` modules to this org

### ISSUE THREAD

**Issue by sstur** [draft-js-utils/draft-js-utils#18]
I'm thinking about moving the following modules from my personal Github `sstur` to `draft-js-utils`. Any thoughts on if that's a good idea?
- draft-js-export-html
- draft-js-import-html
- draft-js-export-markdown
- draft-js-import-markdown
- draft-js-import-element (used by import-html and import-markdown)

**Comment by adrianmcli** [comment]
Funny you should mention this. I was looking at your libraries yesterday and thinking the same thing. It'd be really nice to have one amazing library of functions and tools for working with Draft JS. That's a project that I'd love to contribute to.
