### ISSUE TITLE
Setting flow up properly

### ISSUE THREAD

**Issue by johanneslumpe** [draft-js-utils/draft-js-utils#4]
@sstur You are using flow within your files, but the repo does not reference flow as dev dependency, nor is there any npm command to type check the code. Would you be up for fixing that? :)

**Comment by sstur** [comment]
Good catch. Ill fix it and also will review the diffs you sent. Much appreciated!

**Comment by johanneslumpe** [comment]
Of course - we all have to work on this together now :)

**Comment by johanneslumpe** [comment]
@sstur Had time to look at this yet?

**Comment by sstur** [comment]
Sorry @johanneslumpe. Will do so now.

**Comment by sstur** [comment]
Done. You can do `npm run typecheck` or you can simply do `npm run test` which will lint and typecheck and run tests. I will add those instructions to the readme.
