### ISSUE TITLE
Agree on approving pull requests

### ISSUE THREAD

**Issue by jaaberg** [draft-js-utils/draft-js-utils#8]
I'm new to doing open source projects, and I just want to know if there are standards or if you have preferences on how PRs get approved. 

Is it enough that one person approves and does the merge? Or should we approve the PR via a comment so that others are able to review it as well? And is it the person approving the PR that is pressing merge, or the person that created the PR?

**Comment by sstur** [comment]
Hi @jaaberg. I like the idea of approving via comment and then if no other objections in, let's say 24hrs or something, then any admin can click merge. If the contributor is also an admin, then I like to let him/her press merge.

That's just my preference, but I'm open to discuss ideas.

**Comment by jaaberg** [comment]
I think that sounds good :)

**Comment by johanneslumpe** [comment]
@jaaberg @sstur sounds fine to me, too.
